name: test
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.GUROBI_LICENSE }}" > ~/gurobi.lic
      - run: julia --project=. -e 'import Pkg; Pkg.instantiate()'
      - run: julia --project=. test/runtests.jl
        env:
          JULIA_CMD: julia
